TOTAL_GROUP_MULTIPLIER = 2.6

old_bss_min = -10
old_bss_max = 10
new_bss_min = 0
new_bss_max = 10

old_css_min = 0
old_css_max = 8
new_css_min = 0
new_css_max = 10

old_nvd_min = 0
old_nvd_max = 8
new_nvd_min = 0
new_nvd_max = 10

COMP_DICT = {
    "google": "Google LLC",
    "cloudfare": "Cloudflare, Inc.",
    "akamai": "Akamai Technologies, Inc.",
    "facebook": "Facebook, Inc.",
}
QUERY = """
SELECT 
  EXTRACT (date
  FROM
      PARSE_TIMESTAMP('%Y%m%d%H%M%S',CAST(date AS string))) AS Date,
  CAST(SPLIT(V2Tone, ",") [
  OFFSET
      (0)] AS FLOAT64) AS tone, DocumentIdentifier
  FROM
  `gdelt-bq.gdeltv2.gkg_partitioned`
  WHERE
"""

FILL_WITH_NA = [
    "company",
    "hostname",
    "dp_matching_fields",
    "dp_db",
    "dp_continent",
    "dp_country",
    "dp_region",
    "dp_zip_code",
    "dp_city",
    "dp_address",
    "dp_addresses",
    "dp_company_name",
    "dp_company_type",
    "dp_legal_entity",
    "dp_business_registry_number",
    "dp_iban_number",
    "dp_bic_number",
    "dp_tax_number",
    "dp_phone_number",
    "dp_secondary_phone_numbers",
    "dp_email_address",
    "dp_secondary_email_addresses",
    "dp_contactable",
    "dp_response",
    "dp_title",
    "dp_description",
    "dp_keywords",
    "dp_developed_website",
    "dp_website_type",
    "dp_category",
    "dp_sic_code",
    "dp_secondary_sic_codes",
    "dp_sic_major_group",
    "dp_sic_division",
    "dp_logo",
    "dp_language",
    "dp_multi_language",
    "dp_authors",
    "dp_privacy_sensitive",
    "dp_page_types",
    "dp_website_state",
    "dp_online_store",
    "dp_shopping_cart_system",
    "dp_trustmarks",
    "dp_delivery_services",
    "dp_payment_methods",
    "dp_payment_providers",
    "dp_currency",
    "dp_heartbeat",
    "dp_trust_grade",
    "dp_traffic_countries",
    "dp_cross_border",
    "dp_analytics_id",
    "dp_brand_names",
    "dp_analytics",
    "dp_ad_network",
    "dp_social_media_types",
    "dp_social_media_widgets",
    "dp_social_media_profiles",
    "dp_live_chat_software",
    "dp_crm",
    "dp_email_services",
    "dp_tld_suggestions",
    "dp_cms",
    "dp_scripting_language",
    "dp_seo_summary",
    "dp_flash",
    "dp_html_version",
    "dp_generator",
    "dp_mobile_version",
    "dp_mobile_app",
    "dp_maps",
    "dp_libraries",
    "dp_rendered_hostnames",
    "dp_rendered_cookie_hostnames",
    "dp_scanrequest_id",
    "dp_hostname",
    "dp_top_level_domain",
    "dp_top_level_domain_type",
    "dp_new_generic_top_level_domain_category",
    "dp_subdomain",
    "dp_domain",
    "dp_zone_file",
    "dp_idn",
    "dp_idn_parts",
    "dp_linked_subdomains",
    "dp_forwarding_domains",
    "dp_hosting_country",
    "dp_ip_address",
    "dp_ipv6_address",
    "dp_as_number",
    "dp_hosting_company",
    "dp_registrar",
    "dp_reseller",
    "dp_dns_ns_domain",
    "dp_dns_ns_nameservers",
    "dp_dns_mx_domain",
    "dp_dns_txt",
    "dp_dnssec",
    "dp_dns_cname",
    "dp_operating_system",
    "dp_webserver",
    "dp_http_headers",
    "dp_control_panel",
    "dp_server_signature",
    "dp_ssl_certificate",
    "dp_ssl_issuer_organization",
    "dp_ssl_issuer_common_name",
    "dp_ssl_type",
    "dp_cdn",
    "dp_video",
    "dp_parking",
]

FILL_WITH_SPECIFIC_DATE = [
    "dp_date_added",
    "dp_date_first_found",
    "dp_date_last_analyzed",
    "dp_date_removed",
    "dp_ssl_start_date",
    "dp_ssl_end_date",
]

DROP_ROWS = [
    "kodersco.typeform.com",
    "www.atxconventions.com",
    "www.downsizingroadmap.com",
    "www.kerriskissnaturals.com",
    "www.michaelgoos.com",
    "www.microsofft.org",
    "www.sexkontaktguide.com",
    "www.simoneyedoc.com",
    "www.wisestoic.com",
    "www.yahoohdtv.com",
    "www.vcahenderson.com",
]

DROP_ROWS_WEBSITE_STATE = [
    "leadtable.typeform.com",
    "removed,deactivated",
    "ww35.shaiwest.com",
    "www.bangkoksheraton.com",
    "www.drmoldaworkshop.com",
    "www.lastdayliving.com",
    "www.microsoft-billing.org",
    "www.mossestad.no",
    "www.sunithasirivoludmd.com",
    "www.yahoolife.com",
    'yandex-verification: 081a63c88656411c,validity-domain-authentication=qjajdjeuduaja,facebook-domain-verification=ae8i8zqkrkf7bov2c8d2hq5shm6vrf,google-site-verification=m51z9-mlipxnbpoba3wza19vm2jm-9d3ofcgimgvcs0,v=spf1 ip4:96.46.132.200/29 ip4:64.106.255.148 ip4:146.82.220.38 ip4:146.82.220.39" " ip4:146.82.220.40 ip4:146.82.220.41 ip4:146.82.220.42 ip4:146.82.220.230 ip4:146.82.220.231 ip4:174.46.207.111 ip4:12.154.12.144" " ip4:146.82.220.232 ip4:146.82.220.233 ip4:146.82.220.234 ip4:70.62.111.204 ip4:12.51.212.254 ip4:12.154.12.130 ip4:12.216.238.114" " ip4:216.134.217.241 ip4:108.163.212.98 ip4:12.51.212.110 ip4:162.144.34.133 ip4:12.188.244.19 ip4:208.117.52.163/32 include:mail.zendesk.com include:email.freshdesk.com include:spf.protection.outlook.com mx ~all,idz7e/ss1czvmevbmfbxo5+mnpxwar79+7k81uawkgai3mbxpf8kvxf94y5evaqpjftz1bp+4xzypxpxflmmkg==,v=dmarc1;p=none;pct=100;rua=mailto:dmarc-agg@planetart.com,mailto:mkhneku1@ag.dmarcian.com;',
]

SCORE_FEATURES = [
    "dp_average_load_time_ms",
    "dp_changes",
    "dp_cloud_score",
    "dp_domain_name_length",
    "dp_economic_footprint",
    "dp_forwarding_domains_count",
    "dp_html_size_kb",
    "dp_incoming_links",
    "dp_linked_subdomains_count",
    "dp_outgoing_links",
    "dp_pages_indexed",
    "dp_pages",
    "dp_seo_score",
    "dp_score",
    "dp_security_score",
    "dp_site_traffic_estimation_average",
    "dp_site_traffic_estimation",
    "dp_technical_evaluation",
    "dp_traffic_index",
    "dp_trust_score",
    "dp_website_age",
    "dp_ecommerce_certainty",
]

companyListData = [
    "centers for medicare",
    "trulioo",
    "esper",
    "home box office inc",
    "native shoes",
    "avalere health",
    "philip morris",
    "samsung",
    "broward college",
    "fannie mae",
    "el paso",
    "perception point",
    "inovalon inc",
    "drata",
    "arkose labs",
    "cyware",
    "flexa",
    "mckesson",
    "cardinal health",
    "malwarebytes",
    "vida",
    "boeing",
    "hewlett-packard",
    "safebreach",
    "dashlane",
    "innovage",
    "securityscorecard",
    "j.p. morgan chase & co.",
    "lifequote",
    "aura",
    "bank of america corp.",
    "casa",
    "zocdoc",
    "berkshire hathaway",
    "flock safety",
    "attackiq",
    "datagrail",
    "eddie bauer llc",
    "enron",
    "duke energy",
    "protonmail",
    "southwest airlines",
    "wiz",
    "wal-mart stores",
    "forallsecure",
    "bmo",
    "zillow group",
    "home depot",
    "flad architects",
    "claroty",
    "bluevoyant",
    "jumpcloud",
    "teladoc",
    "meta",
    "menlo security",
    "tokenex",
    "illumio",
    "albertsons",
    "merck",
    "ford motor",
    "kroger",
    "cyera",
    "chevrontexaco",
    "stackoverflow",
    "exxon mobil",
    "truora",
    "advanced auto parts",
    "citigroup",
    "abbott",
    "freddie mac",
    "general electric",
    "american international group",
    "network perception",
    "corelight",
    "enveil",
    "verizon communications",
    "intigriti",
    "amazon",
    "google",
    "microsoft",
    "corsha",
    "aol time warner",
    "deep instinct",
    "kmart",
    "general motors",
    "merrill lynch",
    "yahoo",
    "instagram",
    "response teck",
    "edge",
    "nike",
    "target",
    "intuit",
    "american electric power",
    "armo",
    "zignal labs",
    "minut",
    "cobalt",
    "tesla",
    "dynegy",
]
hostListData = [
    "www.cms.gov",
    "trulioo.com",
    "www.esper.io",
    "www.hbo.com",
    "www.nativeshoes.com",
    "avalere.com",
    "www.pmi.com",
    "www.samsung.com",
    "www.boward.edu",
    "fanniemae.com",
    "elpaso.com",
    "www.perception-point.io",
    "www.inovalon.com",
    "drata.com",
    "www.arkoselabs.com",
    "www.cyware.com",
    "flexa.network",
    "mckesson.com",
    "cardinal.com",
    "www.malwarebytes.com",
    "vida.id",
    "www.boeing.com",
    "hp.com",
    "www.safebreach.com",
    "www.dashlane.com",
    "innovage.com",
    "securityscorecard.com",
    "jpmorganchase.com",
    "lifequote.com",
    "www.aura.com",
    "bankofamerica.com",
    "keys.casa",
    "zocdoc.com",
    "berkshirehathaway.com",
    "www.flocksafety.com",
    "www.attackiq.com",
    "www.datagrail.io",
    "eddiebauer.com",
    "enron.com",
    "duke-energy.com",
    "protonmail.com",
    "southwest.com",
    "wiz.io",
    "walmartstores.com",
    "forallsecure.com",
    "www.bmo.com",
    "zillowgroup.com",
    "homedepot.com",
    "flad.com",
    "www.claroty.com",
    "www.bluevoyant.com",
    "jumpcloud.com",
    "teladochealth.com",
    "about.facebook.com",
    "www.menlosecurity.com",
    "www.tokenex.com",
    "www.illumio.com",
    "albertsons.com",
    "merck.com",
    "ford.com",
    "kroger.com",
    "cyera.io",
    "chevron.com",
    "stackoverflow.com",
    "exxonmobil.com",
    "www.truora.com",
    "shop.advanceautoparts.com",
    "citigroup.com",
    "abbott.com",
    "freddiemac.com",
    "ge.com",
    "aig.com",
    "www.network-perception.com",
    "www.corelight.com",
    "www.enveil.com",
    "verizon.com",
    "www.intigriti.com",
    "www.amazon.com",
    "google.com",
    "microsoft.com",
    "www.corsha.com",
    "aoltimewarner.com",
    "www.deepinstinct.com",
    "kmart.com",
    "gm.com",
    "ml.com",
    "yahoo.com",
    "instagram.com",
    "teck.com",
    "edge.app",
    "nike.com",
    "target.com",
    "www.intuit.com",
    "aep.com",
    "armosec.io",
    "zignallabs.com",
    "minut.com",
    "cobalt.io",
    "tesla.com",
    "dynegy.com",
]

dummy_CVE_data = {
    "CVE-2020-10287": [
        {
            "BaseScoreV2:": 6.5,
            "ExploitabilityScoreV2": 8.0,
            "ImpactScoreV2": 6.4,
            "BasescoreV3": 8.8,
            "ExploitabilityScoreV3": 2.8,
            "ImpactScoreV3": 9.4,
        },
        {
            "current": 2.03,
            "highest": {"date": "2020-07-29T00:00:00.000Z", "value": 6.86},
            "previouslyExploited": 5.34,
        },
        {"link": "https://github.com/aliasrobotics/RVD/issues/3326"},
        ["Apache Web"],
    ],
    "CVE-2020-10287": [
        {
            "BaseScoreV2:": 6.5,
            "ExploitabilityScoreV2": 8.0,
            "ImpactScoreV2": 6.4,
            "BasescoreV3": 8.8,
            "ExploitabilityScoreV3": 2.8,
            "ImpactScoreV3": 8.6,
        },
        {
            "current": 2.03,
            "highest": {"date": "2020-07-29T00:00:00.000Z", "value": 6.86},
            "previouslyExploited": 5.34,
        },
        {"link": "https://github.com/aliasrobotics/RVD/issues/3326"},
        ["Cisco Router"],
    ],
    "CVE-2020-1032": [
        {
            "BaseScoreV2:": 6.5,
            "ExploitabilityScoreV2": 8.0,
            "ImpactScoreV2": 6.4,
            "BasescoreV3": 8.8,
            "ExploitabilityScoreV3": 2.8,
            "ImpactScoreV3": 8.8,
        },
        {
            "current": 2.03,
            "highest": {"date": "2020-07-29T00:00:00.000Z", "value": 6.86},
            "previouslyExploited": 5.34,
        },
        {
            "link": "https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2020-1032"
        },
        ["Cisco Router"],
    ],
    "CVE-2020-1036": [
        {
            "BaseScoreV2:": 6.5,
            "ExploitabilityScoreV2": 8.0,
            "ImpactScoreV2": 6.4,
            "BasescoreV3": 8.8,
            "ExploitabilityScoreV3": 2.8,
            "ImpactScoreV3": 7.8,
        },
        {
            "current": 2.03,
            "highest": {"date": "2020-07-29T00:00:00.000Z", "value": 6.86},
            "previouslyExploited": 5.34,
        },
        {
            "link": "https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2020-1036"
        },
        ["asp.net"],
    ],
}


dummy_company_scores = [
    {
        "Name": "Google",
        "Domain": "google.com",
        "Industry": "Software",
        "Status": "Critical",
        "Alert_Type": "CVE_Exposure",
    },
    {
        "Name": "Boeing",
        "Domain": "boeing.com",
        "Industry": "Retail",
        "Status": "High",
        "Alert_Type": "Sentiment",
    },
    {
        "Name": "Microsoft",
        "Domain": "microsoft.com",
        "Industry": "Software",
        "Status": "Medium",
        "Alert_Type": "Dark web",
    },
    {
        "Name": "Shopify",
        "Domain": "shopify.com",
        "Industry": "Retail",
        "Status": "Low",
        "Alert_Type": "Ransomware",
    },
    {
        "Name": "Nike",
        "Domain": "nike.com",
        "Industry": "Retail",
        "Status": "Medium",
        "Alert_Type": "Dark Web",
    },
    {
        "Name": "Addidas",
        "Domain": "addidas.com",
        "Industry": "Retail",
        "Status": "High",
        "Alert_Type": "CVE Exposure",
    },
    {
        "Name": "abbott",
        "Domain": "abbott.com",
        "Industry": "Software",
        "Status": "Low",
        "Alert_Type": "Ransomware",
    },
    {
        "Name": "Tesla",
        "Domain": "tesla.com",
        "Industry": "Software",
        "Status": "Critical",
        "Alert_Type": "Sentiment",
    },
    {
        "Name": "Google",
        "Domain": "google.com",
        "Industry": "Software",
        "Status": "Critical",
        "Alert_Type": "CVE_Exposure",
    },
    {
        "Name": "Boeing",
        "Domain": "boeing.com",
        "Industry": "Retail",
        "Status": "High",
        "Alert_Type": "Sentiment",
    },
    {
        "Name": "Microsoft",
        "Domain": "microsoft.com",
        "Industry": "Software",
        "Status": "Medium",
        "Alert_Type": "Dark web",
    },
    {
        "Name": "Shopify",
        "Domain": "shopify.com",
        "Industry": "Retail",
        "Status": "Low",
        "Alert_Type": "Ransomware",
    },
    {
        "Name": "Nike",
        "Domain": "nike.com",
        "Industry": "Retail",
        "Status": "Medium",
        "Alert_Type": "Dark Web",
    },
    {
        "Name": "Addidas",
        "Domain": "addidas.com",
        "Industry": "Retail",
        "Status": "High",
        "Alert_Type": "CVE Exposure",
    },
    {
        "Name": "abbott",
        "Domain": "abbott.com",
        "Industry": "Software",
        "Status": "Low",
        "Alert_Type": "Ransomware",
    },
    {
        "Name": "Tesla",
        "Domain": "tesla.com",
        "Industry": "Software",
        "Status": "Critical",
        "Alert_Type": "Sentiment",
    },
]
