from enum import Enum


class PipelineType(Enum):
    JSON_PIPELINE = "JSON_PIPELINE"
    DB_PIPELINE = "DB_PIPELINE"


class StageType(Enum):
    START_PREDICTIONS = "START_PREDICTIONS"
    START_TRAINING = "START_TRAINING"


class BatchType(Enum):
    PREDICTED_DATE_BASED = "PREDICTED_DATE_BASED"
    PREDICTED_ALL_HOSTNAMES = "PREDICTED_ALL_HOSTNAMES"
    DATAFRAME_BASED = "DATAFRAME_BASED"
    CRAWLED_WEB_DATE_BASED = "CRAWLED_WEB_DATE_BASED"
    CRAWLED_WEB_ALL_HOSTNAMES = "CRAWLED_WEB_ALL_HOSTNAMES"
